FORMAT: 1A
HOST: http://127.0.0.1:8888/

# API Name

# R 1 [/test1]

## Foo Bar [GET]

+ Request A

  + Headers

    ```
    Foo: Bar
    ```

+ Response 200 (text/plain;charset=UTF-8)

  + Body

    ```
    Hello, World!
    ```